#ques 1
f=open('test.txt','r')
h=f.read()
print(h)
#ques 2
f=open('test.txt')
h=f.read()
j=input("Enter the element to count")
g=h.count(j)
print(j,"occurs ",g,"Times in the file")
#ques 3
f=open('test.txt')
j=open('test1.txt','a+')
h=f.read()
j.write(h)
j.seek(0)
m=j.read()
print(m)
# # ques 4
f=open('test.txt')
g=open('test2.txt')
j=open('newdoc.txt','w+')
h=f.readlines()
l=g.readlines()
for i,q in zip(h,l):
    j.write(str(i))
    j.write(str(q))
j.seek(0)
y=j.read()
print(y)
#ques 5
f=open('test.txt')
t=open('file.txt','w+')
h=f.readlines()
h.sort()
t.write(str(h))
t.seek(0)
o=t.read()
print(o)
